name: Regenerate Gradle Wrapper

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  regenerate-wrapper:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Java (required for Gradle)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'

    # Step 3: Generate the Gradle wrapper files
    - name: Generate Gradle Wrapper
      run: |
        gradle wrapper
        chmod +x gradlew

    # Step 4: Commit the changes back to the repository
    - name: Commit Gradle Wrapper
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.jar
        git commit -m "Regenerate Gradle wrapper files"
        git push